import Cookies from "./cookies.js";
export const cookieNames = Object.freeze({
    allowed: "cookiesAllowed",
    theme: "theme",
});
export const cookies = new Cookies("ds2Checklist_");
export const bonfires = Object.freeze({
    "Things Betwixt": ["Fire Keepers' Dwelling"],
    Majula: ["The Far Fire"],
    "Forest of Fallen Giants": [
        "The Crestfallen's Retreat",
        "Cardinal Tower",
        "Soldier's Rest",
        "The Place Unbeknownst",
    ],
    "Heide's Tower of Flame": ["Heide's Ruin", "Tower of Flame"],
    "Cathedral of Blue": ["The Blue Cathedral"],
    "No Man's Wharf": ["Unseen Path to Heide"],
    "The Lost Bastille": [
        "Exile Holding Cells",
        "McDuff's Workshop",
        "Servants' Quarters",
        "Straid's Cell",
        "The Tower Apart",
    ],
    "Belfry Luna": ["Upper Ramparts"],
    "Sinner's Rise": ["The Saltfort"],
    "Huntsman's Copse": ["Undead Refuge", "Bridge Approach", "Undead Lockaway"],
    "Undead Purgatory": ["Undead Purgatory"],
    "Harvest Valley": ["Poison Pool", "The Mines"],
    "Earthen Peak": [
        "Lower Earthen Peak",
        "Central Earthen Peak",
        "Upper Earthen Peak",
    ],
    "Iron Keep": ["Threshold Bridge", "Ironheart Hall", "Eygil's Idol"],
    "Belfry Sol": ["Belfry Sol"],
    "Shaded Woods": ["Old Akelarre", "Ruined Fork Road", "Shaded Ruins"],
    "Doors of Pharros": ["Gyrm's Respite", "Ordeal's End"],
    "Brightstone Cove Tseldora": [
        "Royal Army Campsite",
        "Chapel Threshold",
        "Lower Brightstone Cove",
    ],
    "Grave of Saints": ["Harval's Resting Place", "Grave Entrance"],
    "The Gutter": ["Upper Gutter", "Central Gutter"],
    "Black Gulch": ["Black Gulch Mouth", "Hidden Chamber"],
    "Drangleic Castle": [
        "King's Gate",
        "Under Castle Drangleic",
        "Forgotten Chamber",
        "Central Castle Drangleic",
    ],
    "Shrine of Amana": [
        "Tower of Prayer",
        "Crumbled Ruins",
        "Rhoy's Resting Place",
        "Rise of the Dead",
    ],
    "Undead Crypt": ["Undead Crypt Entrance", "Undead Ditch"],
    "Aldia's Keep": ["Foregarden", "Ritual Site"],
    "Dragon Aerie": ["Dragon Aerie"],
    "Dragon Shrine": ["Shrine Entrance"],
    "Shulva, Sanctum City": [
        "Sanctum Walk",
        "Tower of Prayer",
        "Priestess' Chamber",
    ],
    "Dragon's Sanctum": [
        "Hidden Sanctum Chamber",
        "Lair of the Imperfect",
        "Sanctum Interior",
    ],
    "Dragon's Rest": ["Sanctum Nadir"],
    "Brume Tower": [
        "Throne Floor",
        "Upper Floor",
        "Foyer",
        "Lowermost Floor",
        "The Smelter Throne",
    ],
    "Iron Passage": ["Iron Hallway Entrance"],
    "Frozen Eleum Loyce": [
        "Outer Wall",
        "Abandoned Dwelling",
        "Inner Wall",
        "Lower Garrison",
        "Expulsion Chamber",
    ],
    "Grand Cathedral": ["Grand Cathedral"],
});
export const npcs = Object.freeze({
    Majula: [
        "Blacksmith Lenigrast",
        "Carhillion of the Fold",
        "Laddersmith Gilligan",
        "Licia of Lindeldt",
        "Maughlin the Armourer",
        "Merchant Hag Melentia",
        "Rosabeth of Melfia",
        "Saulden the Crestfallen Warrior",
        "Stone Trader Chloanne",
        "Sweet Shalquoir",
    ],
    Elsewhere: [
        "Aldia, Scholar of the First Sin",
        "Alsanna, Silent Oracle",
        "Belfry Guard",
        "Benhart of Jugo",
        "Blue Sentinel Targray",
        "Captain Drummond",
        "Chancellor Wellager",
        "Creighton the Wanderer",
        "Cromwell the Pardoner",
        "Darkdiver Grandahl",
        "Felkin the Outcast",
        "Grave Warden Agdayne",
        "Head of Vengarl",
        "Lonesome Gavlan",
        "Lucatiel of Mirrah",
        "Magerold of Lanafir",
        "Manscorpion Tark",
        "Mild Mannered Pate",
        "Royal Sorcerer Navlaan",
        "Sparkling Sisters Dyna and Tillo",
        "Steady Hand McDuff",
        "Straid of Olaphis",
        "Strowen",
        "The Rat King",
        "Titchy Gren",
        "Weaponsmith Ornifex",
    ],
});
