export const storageKeys = Object.freeze({
    theme: "theme",
    tab: "tab",
    cascadeChecked: "cascadeChecked",
    cascadeToggled: "cascadeToggled",
    hideExpandAll: "hideExpandAll",
    hideScrollToTop: "hideScrollToTop",
});

export const trees = Object.freeze({
    bonfires: {
        "Base game": {
            Majula: {
                "The Far Fire": {},
            },
            "Things Betwixt": {
                "Fire Keepers' Dwelling": {},
            },
            "Forest of Fallen Giants": {
                "The Crestfallen's Retreat": {},
                "Cardinal Tower": {},
                "Soldier's Rest": {},
                "The Place Unbeknownst": {},
            },
            "Heide's Tower of Flame": {
                "Heide's Ruin": {},
                "Tower of Flame": {},
            },
            "Cathedral of Blue": {
                "The Blue Cathedral": {},
            },
            "No Man's Wharf": {
                "Unseen Path to Heide": {},
            },
            "The Lost Bastille": {
                "Exile Holding Cells": {},
                "McDuff's Workshop": {},
                "Servants' Quarters": {},
                "Straid's Cell": {},
                "The Tower Apart": {},
            },
            "Sinner's Rise": {
                "The Saltfort": {},
            },
            "Belfry Luna": {
                "Upper Ramparts": {},
            },
            "Huntsman's Copse": {
                "Undead Refuge": {},
                "Bridge Approach": {},
                "Undead Lockaway": {},
            },
            "Undead Purgatory": {
                "Undead Purgatory": {},
            },
            "Harvest Valley": {
                "Poison Pool": {},
                "The Mines": {},
            },
            "Earthen Peak": {
                "Lower Earthen Peak": {},
                "Central Earthen Peak": {},
                "Upper Earthen Peak": {},
            },
            "Iron Keep": {
                "Threshold Bridge": {},
                "Ironheart Hall": {},
                "Eygil's Idol": {},
            },
            "Belfry Sol": {
                "Belfry Sol": {},
            },
            "Shaded Woods": {
                "Old Akelarre": {},
                "Ruined Fork Road": {},
                "Shaded Ruins": {},
            },
            "Doors of Pharros": {
                "Gyrm's Respite": {},
                "Ordeal's End": {},
            },
            "Brightstone Cove Tseldora": {
                "Royal Army Campsite": {},
                "Chapel Threshold": {},
                "Lower Brightstone Cove": {},
            },
            "Grave of Saints": {
                "Harval's Resting Place": {},
                "Grave Entrance": {},
            },
            "The Gutter": {
                "Upper Gutter": {},
                "Central Gutter": {},
            },
            "Black Gulch": {
                "Black Gulch Mouth": {},
                "Hidden Chamber": {},
            },
            "Drangleic Castle": {
                "King's Gate": {},
                "Under Castle Drangleic": {},
                "Forgotten Chamber": {},
                "Central Castle Drangleic": {},
            },
            "Shrine of Amana": {
                "Tower of Prayer": {},
                "Crumbled Ruins": {},
                "Rhoy's Resting Place": {},
                "Rise of the Dead": {},
            },
            "Undead Crypt": {
                "Undead Crypt Entrance": {},
                "Undead Ditch": {},
            },
            "Aldia's Keep": {
                Foregarden: {},
                "Ritual Site": {},
            },
            "Dragon Aerie": {
                "Dragon Aerie": {},
            },
            "Dragon Shrine": {
                "Shrine Entrance": {},
            },
        },
        DLC: {
            "Shulva, Sanctum City": {
                "Sanctum Walk": {},
                "Tower of Prayer": {},
                "Priestess' Chamber": {},
            },
            "Dragon's Sanctum": {
                "Hidden Sanctum Chamber": {},
                "Lair of the Imperfect": {},
                "Sanctum Interior": {},
            },
            "Dragon's Rest": {
                "Sanctum Nadir": {},
            },
            "Brume Tower": {
                "Throne Floor": {},
                "Upper Floor": {},
                Foyer: {},
                "Lowermost Floor": {},
                "The Smelter Throne": {},
            },
            "Iron Passage": {
                "Iron Hallway Entrance": {},
            },
            "Frozen Eleum Loyce": {
                "Outer Wall": {},
                "Abandoned Dwelling": {},
                "Inner Wall": {},
                "Lower Garrison": {},
                "Expulsion Chamber": {},
            },
            "Grand Cathedral": {
                "Grand Cathedral": {},
            },
        },
    },
    bosses: {
        "Base game": {
            "The Last Giant": {
                "Giant Stone Axe": {},
            },
            "The Pursuer": {
                "Pursuer's Greatshield": {},
                "Pursuer's Ultra Greatsword": {},
            },
            Dragonrider: {
                "Dragonrider Bow": {},
                "Dragonrider Greatshield": {},
                "Dragonrider Twinblade": {},
                "Dragonrider's Halberd": {},
            },
            "Old Dragonslayer": {
                "Dragonslayer Spear": {},
            },
            "Flexile Sentry": {
                "Arced Sword": {},
                "Barbed Club": {},
                "Warped Sword": {},
            },
            "Ruin Sentinels": {
                "Heavy Homing Soul Arrow": {},
            },
            "The Lost Sinner": {
                "Soul of the Lost Sinner": {
                    "Lost Sinner's Sword": {},
                },
                "Old Witch Soul": {
                    "Chaos Blade": {},
                    "Flame Weapon": {},
                },
            },
            "Belfry Gargoyles": {
                "Gargoyle Bident": {},
            },
            "Skeleton Lords": {
                "Roaring Halberd": {},
            },
            "Executioner's Chariot": {
                "Chariot Lance": {},
                "Shield Crossbow": {},
            },
            "Covetous Demon": {
                "Bone Scythe": {},
            },
            "Mytha, the Baneful Queen": {
                "Mytha's Bent Blade": {},
            },
            "Smelter Demon": {
                "Aged Smelter Sword": {},
                "Smelter Sword": {},
            },
            "Old Iron King": {
                "Old Iron King Soul": {
                    "Iron King Hammer": {},
                },
                "Old King Soul": {
                    "Blinding Bolt": {},
                    "Dragonslayer Greatbow": {},
                },
            },
            "Scorpioness Najka": {
                "Soul Shower": {},
            },
            "Royal Rat Authority": {
                "Acid Surge": {},
            },
            "Prowling Magus & Congregation": {},
            "The Duke's Dear Freja": {
                "Soul of the Duke's Dear Freja": {
                    "Spider Fang": {},
                    "Spider's Silk": {},
                },
                "Old Paledrake Soul": {
                    "Crystal Soul Spear": {},
                    "Moonlight Greatsword": {},
                },
            },
            "Royal Rat Vanguard": {
                "Toxic Mist": {},
            },
            "The Rotten": {
                "Soul of the Rotten": {
                    "Butcher's Knife": {},
                },
                "Old Dead One Soul": {
                    Numbness: {},
                    "Crypt Blacksword": {},
                },
            },
            Dragonriders: {
                "Dragonrider Bow": {},
                "Dragonrider Greatshield": {},
                "Dragonrider Twinblade": {},
                "Dragonrider's Halberd": {},
            },
            "Looking Glass Knight": {
                "King's Mirror": {},
                "Thorned Greatsword": {},
            },
            "Demon of Song": {
                "Spotted Whip": {},
            },
            "Velstadt, the Royal Aegis": {
                "Sacred Chime Hammer": {},
                "Sacred Oath": {},
            },
            Vendrick: {},
            "Guardian Dragon": {
                "Drakewing Ultra Greatsword": {},
                "Spitfire Spear": {},
            },
            "Ancient Dragon": {},
            "Giant Lord": {
                Repel: {},
            },
            "Throne Defender & Throne Watcher": {
                "Throne Defender Soul": {
                    "Defender Greatsword": {},
                    "Defender's Shield": {},
                },
                "Throne Watcher Soul": {
                    "Watcher Greatsword": {},
                    "Watcher's Shield": {},
                },
            },
            Nashandra: {
                "Bow of Want": {},
                "Chime of Want": {},
                "Scythe of Want": {},
            },
            "Aldia, Scholar of the First Sin": {},
            Darklurker: {
                "Lifedrain Patch": {},
            },
        },
        DLC: {
            "Elana, the Squalid Queen": {
                "Wrathful Axe": {},
            },
            "Sinh, the Slumbering Dragon": {
                "Yorgh's Spear": {},
            },
            "Afflicted Graverobber, Ancient Soldier Varg & Cerah the Old Explorer":
                {},
            "Fume Knight": {
                "Soul of the Fume Knight": {
                    "Fume Sword": {},
                    "Fume Ultra Greatsword": {},
                },
                "Soul of Nadalia, Bride of Ash": {
                    Outcry: {},
                    "Chime of Screams": {},
                },
            },
            "Sir Alonne": {
                "Bewitched Alonne Sword": {},
            },
            "Smelter Demon (Iron King)": {
                "Smelter Sword": {},
                "Aged Smelter Sword": {},
            },
            "Aava, the King's Pet": {
                "Ivory Straight Sword": {},
            },
            "Burnt Ivory King": {
                "Ivory King Ultra Greatsword": {},
            },
            "Lud, the King's Pet & Zallen, the King's Pet": {
                "Soul of Lud, the King's Pet": {
                    "Loyce Greatsword": {},
                },
                "Soul of Zallen, the King's Pet": {
                    "Loyce Shield": {},
                },
            },
        },
    },
    "dyna-and-tillo": {
        "Prism Stone": {
            "Amber Herb": {},
            "Fading Soul": {},
            "Homeward Bone": {},
            "Human Effigy": {},
            Lifegem: {},
            Rubbish: {},
            "Small Blue Burr": {},
            "Small Orange Burr": {},
            "Small Yellow Burr": {},
            "Titanite Shard": {},
        },
        "Small Smooth & Silky Stone": {
            "Amber Herb": {},
            "Bleed Stone": {},
            Boltstone: {},
            "Channeler's Trident": {},
            "Cracked Blue Eye Orb": {},
            "Cracked Red Eye Orb": {},
            "Crimson Water": {},
            "Darknight Stone": {},
            "Demon's Great Hammer": {},
            "Divine Blessing": {},
            Faintstone: {},
            "Firedrake Stone": {},
            "Human Effigy": {},
            Lifegem: {},
            "Magic Stone": {},
            "Old Mundane Stone": {},
            "Old Whip": {},
            "Petrified Dragon Bone": {},
            "Poison Stone": {},
            "Raw Stone": {},
            "Soul of a Lost Undead": {},
            "Soul of a Proud Knight": {},
            "Titanite Chunk": {},
            "Titanite Shard": {},
            "Titanite Slab": {},
            "Twinkling Titanite": {},
            "White Ring": {},
        },
        "Smooth & Silky Stone": {
            "Bleed Stone": {},
            Boltstone: {},
            "Channeler's Trident": {},
            "Cracked Blue Eye Orb": {},
            "Cracked Red Eye Orb": {},
            "Crimson Water": {},
            "Darknight Stone": {},
            "Demon's Great Hammer": {},
            "Divine Blessing": {},
            Faintstone: {},
            "Firedrake Stone": {},
            "Human Effigy": {},
            "Magic Stone": {},
            "Old Mundane Stone": {},
            "Old Whip": {},
            "Petrified Dragon Bone": {},
            "Poison Stone": {},
            "Raw Stone": {},
            "Soul of a Proud Knight": {},
            "Titanite Chunk": {},
            "Titanite Slab": {},
            "Twinkling Titanite": {},
            "White Ring": {},
        },
        "Petrified Something": {
            "Channeler's Trident": {},
            "Demon's Great Hammer": {},
            "Old Whip": {},
            "Petrified Dragon Bone": {},
            "Titanite Slab": {},
            "Twinkling Titanite": {},
            "White Ring": {},
        },
    },
    npcs: {
        "Multiple locations": {
            "Aldia, Scholar of the First Sin": {},
            "Belfry Guard": {},
            "Benhart of Jugo": {},
            "Captain Drummond": {},
            "Creighton the Wanderer": {},
            "Darkdiver Grandahl": {
                "Bonfire Ascetic x10": {},
                "Cast Light": {},
                "Dark Hail": {},
                "Dark Orb": {},
                Darkstorm: {},
                "Human Effigy x3": {},
                "Profound Still": {},
            },
            "Lonesome Gavlan": {
                "Poison Arrow x20": {},
                "Poison Moss x20": {},
                "Poison Throwing Knife x20": {},
                "Ring of Giants (Doors of Pharros)": {},
                "Ring of Giants (Harvest Valley)": {},
                "Ring of Giants (No-Man's Wharf)": {},
                "Rotten Pine Resin x20": {},
            },
            "Lucatiel of Mirrah": {},
            "Mild Mannered Pate": {},
            "The Rat King": {},
            Vendrick: {},
        },
        Majula: {
            "Blacksmith Lenigrast": {
                "Heavy Bolt x50": {},
                "Iron Arrow x50": {},
                "Repair Powder": {},
                "Titanite Shard x10": {},
            },
            "Carhillion of the Fold": {
                "Amber Herb x10": {},
                "Clear Bluestone Ring": {},
                "Great Heavy Soul Arrow": {},
                "Great Soul Arrow": {},
                "Heavy Soul Arrow": {},
                "Magic Weapon": {},
                Shockwave: {},
                "Simpleton's Spice": {},
                "Soul Arrow": {},
                "Soul Spear Barrage": {},
                "Spell Quartz Ring": {},
                "Twilight Herb x5": {},
                Yearn: {},
            },
            "Laddersmith Gilligan": {
                "Ladder Miniature": {},
                "Large Ladder": {},
                "Medium Ladder": {},
                "Small Ladder": {},
            },
            "Licia of Lindeldt": {
                "Caressing Prayer": {},
                Force: {},
                "Great Heal Excerpt": {},
                Guidance: {},
                Heal: {},
                Homeward: {},
                "Lightning Spear": {},
                "Med Heal": {},
                Replenishment: {},
                "Resplendent Life": {},
                "Ring of Prayer": {},
            },
            "Maughlin the Armourer": {
                "Ivory King Armor": {},
                "Ivory King Gauntlets": {},
                "Ivory King Helm": {},
                "Ivory King Leggings": {},
                "Looking Glass Armor": {},
                "Looking Glass Gauntlets": {},
                "Looking Glass Leggings": {},
                "Looking Glass Mask": {},
                "Moon Butterfly Cuffs": {},
                "Moon Butterfly Hat": {},
                "Moon Butterfly Skirt": {},
                "Moon Butterfly Wings": {},
                "Penal Handcuffs": {},
                "Penal Mask": {},
                "Penal Skirt": {},
                "Penal Straightjacket": {},
                "Smelter Demon Armor": {},
                "Smelter Demon Gauntlets": {},
                "Smelter Demon Helm": {},
                "Smelter Demon Leggings": {},
                "Throne Defender Armor": {},
                "Throne Defender Gauntlets": {},
                "Throne Defender Helm": {},
                "Throne Defender Leggings": {},
                "Throne Watcher Armor": {},
                "Throne Watcher Gauntlets": {},
                "Throne Watcher Helm": {},
                "Throne Watcher Leggings": {},
                "Velstadt's Armor": {},
                "Velstadt's Gauntlets": {},
                "Velstadt's Helm": {},
                "Velstadt's Leggings": {},
            },
            "Merchant Hag Melentia": {
                "Agdayne's Black Robe": {},
                "Agdayne's Cuffs": {},
                "Amber Herb x3": {},
                "Benhart's Armor": {},
                "Benhart's Boots": {},
                "Benhart's Gauntlets": {},
                "Benhart's Knight Helm": {},
                "Benhart's Parma": {},
                "Black Boots": {},
                "Black Gloves": {},
                "Black Robes": {},
                "Brightbug x3": {},
                "Cale's Leather Armor": {},
                "Cale's Shoes": {},
                "Chaos Boots": {},
                "Chaos Gloves": {},
                "Chaos Robe": {},
                "Creighton's Chain Gloves": {},
                "Creighton's Chain Leggings": {},
                "Creighton's Chainmail": {},
                Darkdrift: {},
                "Fragrant Branch of Yore": {},
                Heal: {},
                "Hexer's Boots": {},
                "Hexer's Gloves": {},
                "Hexer's Hood": {},
                "Hexer's Robes": {},
                "Human Effigy x5": {},
                "Lenigrast's Key": {},
                "Lifegem x10": {},
                "Lucatiel's Gloves": {},
                "Lucatiel's Trousers": {},
                "Lucatiel's Vest": {},
                "Mirrah Greatsword": {},
                "Nahr Alma Robes": {},
                "Pate's Armor": {},
                "Pate's Gloves": {},
                "Pate's Helm": {},
                "Pate's Shield": {},
                "Pate's Trousers": {},
                "Pharros Lockstone": {},
                "Radiant Lifegem x10": {},
                "Saint's Dress": {},
                "Saint's Hood": {},
                "Saint's Long Gloves": {},
                "Saint's Trousers": {},
                "Scythe of Nahr Alma": {},
                "Soul Arrow": {},
                "Targray's Armor": {},
                "Targray's Helm": {},
                "Targray's Leggings": {},
                "Targray's Manifers": {},
            },
            "Rosabeth of Melfia": {
                Combustion: {},
                "Dark Quartz Ring": {},
                "Fire Orb": {},
                "Fire Seed x3": {},
                Fireball: {},
                "Flame Quartz Ring": {},
                "Flash Sweat": {},
                "Iron Flesh": {},
                "Poison Mist": {},
                "Thunder Quartz Ring": {},
            },
            "Saulden the Crestfallen Warrior": {},
            "Stone Trader Chloanne": {
                "Bleed Stone x3": {},
                "Boltstone x3": {},
                "Bonfire Ascetic": {},
                "Darknight Stone x3": {},
                "Dead Again": {},
                "Faintstone x3": {},
                "Firedrake Stone x3": {},
                "Large Titanite Shard x10": {},
                "Magic Stone x3": {},
                "Old Mundane Stone x3": {},
                "Petrified Dragon Bone x3": {},
                "Poison Stone x3": {},
                "Raw Stone x3": {},
                "Soul Appease": {},
                "Titanite Chunk x10": {},
                "Titanite Shard x10": {},
                "Titanite Slab": {},
                "Twinkling Titanite x3": {},
            },
            "Sweet Shalquoir": {
                "Alluring Skull x10": {},
                "Flying Feline Boots": {},
                "Homeward Bone x10": {},
                "Lloyd's Talisman x10": {},
                "Name-engraved Ring": {},
                "Prism Stone x10": {},
                "Redeye Ring": {},
                "Ring of the Evil Eye": {},
                "Ring of Whispers": {},
                "Silvercat Ring": {},
            },
        },
        "Things Betwixt": {
            "Sparkling Sisters Dyna and Tillo": {},
            Strowen: {},
        },
        "Cathedral of Blue": {
            "Blue Sentinel Targray": {
                "Emit Force": {},
                "Heavenly Thunder": {},
                "Monastery Charm x3": {},
            },
        },
        "The Lost Bastille": {
            "Steady Hand McDuff": {
                "Bastard Sword": {},
                Greataxe: {},
                "Light Crossbow": {},
                "Long Bow": {},
                "Repair Powder": {},
                "Royal Kite Shield": {},
                Scythe: {},
                Uchigatana: {},
                "Winged Spear": {},
            },
            "Straid of Olaphis": {
                Affinity: {},
                "Agape Ring": {},
                "Armor of the Forlorn": {},
                "Cast Light": {},
                "Dark Fog": {},
                "Dark Hail": {},
                "Dark Orb": {},
                "Flame Swathe": {},
                "Gauntlets of the Forlorn": {},
                "Great Lightning Spear": {},
                "Greatsword of the Forlorn": {},
                "Homing Soul Arrow": {},
                "Hood of the Forlorn": {},
                "Leggings of the Forlorn": {},
                "Lingering Dragoncrest Ring": {},
                "Lingering Flame": {},
                "Resplendent Life": {},
                "Ring of Knowledge": {},
                "Rouge Water x3": {},
                "Scythe of the Forlorn": {},
                "Strong Magic Shield": {},
                "Sunlight Blade": {},
                Unveil: {},
            },
        },
        "Huntsman's Copse": {
            "Felkin the Outcast": {
                "Dark Orb": {},
                "Dark Weapon": {},
                "Great Resonant Soul": {},
                "Magic Barrier": {},
                "Resonant Flesh": {},
                "Resonant Soul": {},
                "Resonant Weapon": {},
                "Ring of Life Protection": {},
            },
        },
        "Undead Purgatory": {
            "Titchy Gren": {
                "Bone Crown": {},
                "Bone King Cuffs": {},
                "Bone King Robe": {},
                "Bone King Skirt": {},
                "Cracked Red Eye Orb x5": {},
                "Delicate String": {},
                "Executioner Armor": {},
                "Executioner Gauntlets": {},
                "Executioner Helm": {},
                "Executioner Leggings": {},
                "Fire Whip": {},
                Firestorm: {},
                "Great Combustion": {},
                "Red Sign Soapstone": {},
            },
        },
        "Iron Keep": {
            "Magerold of Lanafir": {
                "Alonne's Armor": {},
                "Alonne's Gauntlets": {},
                "Alonne's Helm": {},
                "Alonne's Leggings": {},
                "Cursebite Ring": {},
                "Dark Hail": {},
                Darkstorm: {},
                "Dragonrider Armor": {},
                "Dragonrider Gauntlets": {},
                "Dragonrider Helm": {},
                "Dragonrider Leggings": {},
                "Fall Control": {},
                "Fragrant Branch of Yore": {},
                "Great Heavy Soul Arrow": {},
                "Great Soul Arrow": {},
                "Green Blossom x10": {},
                "Heavy Soul Arrow": {},
                "Hello Carving": {},
                "Human Effigy": {},
                "I'm Sorry Carving": {},
                "Raime's Armor": {},
                "Raime's Gauntlets": {},
                "Raime's Helm": {},
                "Raime's Leggings": {},
                "Repair Powder": {},
                "Rusted Coin x5": {},
                "Soul Arrow": {},
                "Thank You Carving": {},
                "Very Good! Carving": {},
            },
        },
        "Shaded Woods": {
            "Head of Vengarl": {
                "Magic Barrier": {},
                "Red Rust Scimitar": {},
                "Red Rust Shield": {},
                "Red Rust Sword": {},
            },
            "Manscorpion Tark": {},
        },
        "Brightstone Cove Tseldora": {
            "Cromwell the Pardoner": {
                "Bloodbite Ring": {},
                "Caressing Prayer": {},
                "Cursebite Ring": {},
                "Emit Force": {},
                Force: {},
                "Great Heal": {},
                "Heavenly Thunder": {},
                Perseverance: {},
                "Poisonbite Ring": {},
                Replenishment: {},
                "Scraps of Life": {},
                "White Priest Gloves": {},
                "White Priest Headpiece": {},
                "White Priest Robe": {},
                "White Priest Skirt": {},
            },
            "Weaponsmith Ornifex": {
                "Amber Herb x10": {},
                "Fall Control": {},
                "Green Blossom x10": {},
                "Homing Soul Arrow": {},
                "Homing Soulmass": {},
            },
        },
        "Drangleic Castle": {
            "Chancellor Wellager": {
                "Black Flamestone Dagger": {},
                "Black Flamestone Parma": {},
                "Bound Hand Axe": {},
                "Bound Wooden Shield": {},
                "Bountiful Sunlight": {},
                "Bracing Knuckle Ring +1": {},
                "Crescent Sickle": {},
                "Curved Twinblade": {},
                "Divine Blessing": {},
                "Great Chaos Fireball": {},
                "Great Magic Barrier": {},
                "Homunculus Mace": {},
                "Homunculus Wooden Shield": {},
                "Old Radiant Lifegem x10": {},
                "Spirit Tree Shield": {},
                "Transgressor's Leather Shield": {},
                "Transgressor's Staff": {},
                "Wilted Dusk Herb x10": {},
                "Wrath of the Gods": {},
                "Yellow Quartz Longsword": {},
                "Yellow Quartz Shield": {},
            },
        },
        "Undead Crypt": {
            "Grave Warden Agdayne": {
                "Elizabeth Mushroom x13": {},
                "Human Effigy x13": {},
                "Insolent Armor": {},
                "Insolent Boots": {},
                "Insolent Gloves": {},
                "Insolent Helm": {},
                "Ring of Thorns +1": {},
                "Shield of the Insolent": {},
                "Soul Appease": {},
                "Soul Spear": {},
                "Soul Vortex": {},
                Warmth: {},
            },
        },
        "Aldia's Keep": {
            "Royal Sorcerer Navlaan": {
                "Bonfire Ascetic x10": {},
                "Crimson Water x5": {},
                "Dragon Charm x5": {},
                "Thunder Quartz Ring": {},
            },
        },
        "Grand Cathedral": {
            "Alsanna, Silent Oracle": {},
        },
    },
    secrets: {
        "Crystal Lizards": {
            "Forest of Fallen Giants": {
                "Before the Last Giant": {},
            },
            "No Man's Wharf": {
                "Behind the room with the poison jars": {},
            },
            "Huntsman's Copse": {
                "On the cliff before the Skeleton Lords": {},
            },
            "Harvest Valley": {
                "Past a boarded up path": {},
            },
            "Iron Keep": {
                "In the room with moveable platforms": {},
            },
            "Grave of Saints": {
                "On a rope bridge": {},
            },
            "Shaded Woods": {
                "In the ruins near Manscorpion Tark": {},
            },
            "Doors of Pharros": {
                "After Gavlan": {},
            },
            "Brightstone Cove Tseldora": {
                "On top of a pillar after fighting the Prowling Magus": {},
                "On the balcony past Pate and Creighton": {},
            },
            "Drangleic Castle": {
                "Before the entrance": {},
            },
            "Dragon Aerie": {
                "Near the 1st drake": {
                    "On the plateau (x4)": {},
                    "In the tunnel under the plateau": {},
                    "On a ledge": {},
                },
                "Near the 2nd drake (x3)": {},
                "Near the 3rd drake": {
                    "On the ground": {},
                    "On a ledge": {},
                },
            },
        },
        "Fragrant Branch of Yore": {
            "Things Betwixt": {
                "Area with Basilisks, Ogres, and Estus Flask Shard": {},
            },
            Majula: {
                "Rosabeth of Melfia at the entrance to the Shaded Woods": {},
            },
            "Heide's Tower of Flame": {
                "Room with Estus Flask Shard and the Knight Set": {},
            },
            "The Lost Bastille": {
                "Path to the Ruin Sentinels": {},
                "Straid of Olaphis in his cell": {},
            },
            "Shaded Woods": {
                "Lion that drops the Fang Key": {},
                "Chest with Repair": {},
                "Lion with the Warlock Mask": {},
                "Chest with the Lion Mage Set and another branch": {},
                "Vengarl's Body miniboss": {},
            },
            "Black Gulch": {
                "Entrance to the Hidden Chamber bonfire": {},
            },
            "Shrine of Amana": {
                "Access to the Rise of the Dead bonfire": {},
            },
            "Aldia's Keep": {
                "Ogre holding the Dragon Acolyte Mask": {},
                "Undead with Elizabeth Mushrooms and Wilted Dusk Herbs": {},
                "Undead with two Bonfire Ascetics": {},
            },
            "Dragon Aerie": {
                "Entrance to the first Guardian Dragon platform": {},
            },
        },
        "Hidden Moths": {
            "Lost Bastille": {
                "Servants' Quarters": {},
            },
            "Huntsman's Copse": {
                "Undead Refuge": {},
                "Bridge Approach": {},
                "Undead Lockaway": {},
            },
            "Earthen Peak": {
                "Central Earthen Peak": {},
            },
            "The Gutter": {
                "Upper Gutter": {},
            },
            "Shaded Woods": {
                "Shaded Ruins (x3)": {},
            },
            "Brightstone Cove Tseldora": {
                "Chapel Threshold": {},
            },
            "Shrine of Amana": {
                "Crumbled Ruins": {},
                "Rhoy's Resting Place": {},
                "Rise of the Dead": {},
            },
            "Undead Crypt": {
                "Undead Ditch": {},
            },
            "Aldia's Keep": {
                "Foregarden Bonfire": {},
            },
        },
        "Illusory Walls": {
            "Forest of Fallen Giants": {
                "Sorcerer's Staff": {},
                "Amber Herb": {},
                "Cardinal Tower Bonfire shortcut": {},
            },
            "No-Man's Wharf": {
                "Firebomb x3": {},
                "Large Titanite Shard": {},
                "Crystal Lizard": {},
                "Fading Soul": {},
                "Soul of a Nameless Soldier": {},
                "Large Soul of a Nameless Soldier": {},
                "Royal Soldier's Ring": {},
            },
            "Lost Bastille": {
                "In Ruin Sentinels boss room": {
                    "Rusted Coin": {},
                    "Target Shield": {},
                    "Homeward Bone x3": {},
                    Hush: {},
                    "Rouge Water": {},
                },
                "Elevator cages": {},
                "Archdrake Robes": {},
                "Archdrake Shield": {},
                "Bracing Knuckle Ring": {},
                "Soul of a Brave Warrior": {},
                "Golden Wing Shield": {},
            },
            "Sinners' Rise": {
                "Northern Ritual Band": {},
                "Bleed Stone": {},
            },
            "Huntsman's Copse": {
                "Ricard's Rapier": {},
            },
            "Harvest Valley": {
                "Old Knight Pike": {},
                "Old Knight Greatshield": {},
                "Soul of a Lost Undead": {},
                Torch: {},
                "Radiant Lifegem": {},
                "Smooth & Silky Stone": {},
            },
            "Earthen Peak": {
                "Spell Quartz Ring +1": {},
                "Petrified Something": {},
                "Upper Earthen Peak Bonfire": {},
            },
            "Iron Keep": {
                "Flaming arrows x20": {},
                "Black Knight Greatsword": {},
                "Protective Chime": {},
                "Grand Spirit Tree Shield": {},
            },
            "Brightstone Cove Tseldora": {
                "Estus Flask Shard": {},
            },
            "Drangleic Castle": {
                "Under Castle Drangleic Bonfire": {},
                "Faraam Set": {},
                "Forgotten Chamber Bonfire": {},
            },
            "Undead Crypt": {
                Avelyn: {},
                "Heavy Bolt x15": {},
                "Olenford's Staff": {},
                "Great Lightning Spear": {},
            },
            "Aldia's Keep": {
                "Ritual Site Bonfire": {},
                "Malformed Shell": {},
            },
            "Memory of Orro (Forest of Fallen Giants)": {
                "Steel Set": {},
                "Fire Seed": {},
            },
            "Shulva - Sanctum City": {
                "Sanctum Interior Bonfire": {},
            },
            "Brume Tower": {
                "Old Radiant Lifegem x4": {},
                "Wilted Dusk Herb x4": {},
                "Soul Vessel x2": {},
                "Hollow Skin": {},
            },
        },
        "Invisible Hollows": {
            "Forest of Fallen Giants": {
                "Near the firebomb throwers above the courtyard": {},
            },
            "No Man's Wharf": {
                "By a house near the Pharros' Contraption": {},
            },
            "The Lost Bastille": {
                "Against a broken stone to the left of a chest": {},
                "In the cell next to Straid's cell": {},
            },
            "Sinner's Rise": {
                "In the first jail cell on the upper left": {},
            },
            "Huntsman's Copse": {
                "In the building after the Undead Refuge bonfire": {},
            },
            "Shaded Woods": {
                "To the left of the King's Gate": {},
            },
            "Doors of Pharros": {
                "In the alcove with the sitting dwarf": {},
            },
            "The Gutter": {
                "On the slanted walkway before the first bonfire": {},
                "On top of the house with the mimic": {},
                "Underneath a platform with a chest": {},
                "To the right of the fog wall before the second bonfire": {},
                "Below the second bonfire on a platform with a brazier": {},
            },
            "Drangleic Castle": {
                "Against the castle wall to the left of the main gate": {},
                "In a guarded treasure room with Sublime Bone Dust": {},
                "Outside the cage with the Milfanito": {},
            },
            "Shrine of Amana": {
                "Outside the building with the second bonfire": {},
                "In the deep water before the Demon of Song boss room": {},
            },
            "Undead Crypt": {
                "Left alcove in the entrance": {},
                "In the room with the witches near the left staircase": {},
                "On the stairs before Agdayne": {},
                "On the wall to the right of Agdayne": {},
                "On a platform on the left past Agdayne's room": {},
                "At the entrance to the hallway with the ghosts": {},
                "In the room with a hole in the middle": {
                    "Near the third statue on the left": {},
                    "Near the third statue on the right": {},
                },
                "In the bell room before Velstadt": {},
                "In the corridor before Velstadt": {
                    "On the left": {
                        "Between the third and fourth pillar from the boss room":
                            {},
                    },
                    "On the right": {
                        "Between the wall and the second pillar (x2)": {},
                        "Near to the fifth pillar from the boss room": {},
                        "Near the pillar closest to the boss room": {},
                    },
                },
            },
            "Aldia's Keep": {
                "In the room with the lever after the dragon skeleton": {},
                "By the elevator after the Guardian Dragon boss room": {},
            },
        },
        "Pharros' Lockstones": {
            "Forest of Fallen Giants": {
                "Titanite Slab": {},
                "Chloranthy Ring": {},
            },
            "Lost Bastille": {
                "Belfry Luna entrance": {},
                "Soul Vessel": {},
            },
            "Earthen Peak": {
                "Poisonbite Ring": {},
                "Soul of a Proud Knight": {},
            },
            "Iron Keep": {
                "Belfry Sol entrance": {},
            },
            "Doors of Pharros": {
                "Santier's Spear": {},
            },
            "Grave of Saints": {
                "Poison Moss x2": {},
                "Whisper of Despair": {},
                Torch: {},
            },
            "Shrine of Amana": {
                "Helix Halberd": {},
            },
            "Undead Crypt": {
                "Olenford's Staff": {},
                "Great Lightning Spear": {},
            },
            "Dragon Shrine": {
                "Mask of Judgement": {},
                "Robe of Judgement": {},
                "Manchettes of Judgement": {},
                "Tights of Judgement": {},
            },
            "Memory of Orro": {
                "Steel Helm": {},
                "Steel Armor": {},
                "Steel Gauntlets": {},
                "Steel Leggings": {},
                "Fire Seed": {},
            },
            "Frozen Elyseum Loyce": {
                "Durgo's Hat": {},
            },
        },
    },
});
